spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: config-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE:discovery-service}:8761/eureka/
---
spring:
  profiles: docker
  application:
    name: config-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE:discovery-service}:8761/eureka/
