spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
zuul:
  ignored-services: '*'
  ignored-patterns: /**/api/**
  add-proxy-headers: true
  routes:
    psycho-test-service:
      path: /psychoTest/**
      service-id: psycho-test-service
      stripPrefix: false
    travel-destination-service:
      path: /travelDestination/**
      service-id: travel-destination-service
      stripPrefix: false
    user-service:
      path: /user/**
      service-id: user-service
      sensitive-headers:
      stripPrefix: false
security:
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order: 3
      jwt:
        key-value: aTokenSigningKey
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
---
spring:
  profiles: development
  application:
    name: edge-service
zuul:
  ignored-services: '*'
  ignored-patterns: /**/api/**
  add-proxy-headers: true
  routes:
    psycho-test-service:
      path: /psychoTest/**
      service-id: psycho-test-service
      stripPrefix: false
    travel-destination-service:
      path: /travelDestination/**
      service-id: travel-destination-service
      stripPrefix: false
    user-service:
      path: /user/**
      service-id: user-service
      sensitive-headers:
      stripPrefix: false
security:
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order: 3
      jwt:
        key-value: aTokenSigningKey
---
spring:
  profiles: docker
  application:
    name: edge-service
zuul:
  ignored-services: '*'
  ignored-patterns: /**/api/**
  add-proxy-headers: true
  routes:
    psycho-test-service:
      path: /psychoTest/**
      service-id: psycho-test-service
      stripPrefix: false
    travel-destination-service:
      path: /travelDestination/**
      service-id: travel-destination-service
      stripPrefix: false
    user-service:
      path: /user/**
      service-id: user-service
      sensitive-headers:
      stripPrefix: false
security:
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order: 3
      jwt:
        key-value: aTokenSigningKey
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
