spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    order-service: /order/**
    shopping-cart-service: /shoppingcart/**
    travel-destination-service: /travelDestination/**
    user-service: /user/**
security:
  oauth2:
    resource:
      jwt:
        key-value: aTokenSigningKey
#      userInfoUri: ${vcap.services.user-service.credentials.uri:http://localhost:8181}/user
#  ignored: /oauth/**
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
---
spring:
  profiles: development
  application:
    name: edge-service
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    order-service: /order/**
    shopping-cart-service: /shoppingcart/**
    travel-destination-service: /travelDestination/**
    user-service: /user/**
security:
  oauth2:
    resource:
      jwt:
        key-value: aTokenSigningKey
#      userInfoUri: http://localhost:8181/user
#  ignored: /oauth/**
---
spring:
  profiles: docker
  application:
    name: edge-service
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    psycho-test-service: /psychoTest/**
    shopping-cart-service: /shoppingcart/**
    travel-destination-service: /travelDestination/**
    user-service: /user/**
security:
  oauth2:
    resource:
      jwt:
        key-value: aTokenSigningKey
#      userInfoUri: http://${DOCKER_IP:192.168.99.100}:8181/user
#  ignored: /oauth/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
