spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
server:
  port: 8383
  contextPath: /psychoTest
security:
  oauth2:
    resource:
      jwt:
        key-value: aTokenSigningKey
    client:
      client-id: acme
---
spring:
  profiles: development
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
server:
  port: 8383
  contextPath: /psychoTest
security:
  oauth2:
    resource:
      jwt:
        key-value: aTokenSigningKey
    client:
      client-id: acme
logging.level.org.springframework.security: DEBUG
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/dev
    username: root
    password: dbpass
    initialize: true
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8383
  contextPath: /psychoTest
security:
  oauth2:
    resource:
      jwt:
        key-value: aTokenSigningKey
    client:
      client-id: acme
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  application:
    name: travel-destination-service
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
security:
  oauth2:
    resource:
      jwt:
        key-value: aTokenSigningKey
    client:
      client-id: acme
      access-token-uri: http://localhost:8787
