spring:
  profiles: docker
  application:
    name: recommendation-service
server:
  port: 7777
security:
  oauth2:
    resource:
      filter-order: 3
      jwt:
        key-value: aTokenSigningKey
    client:
      client-id: acme
management:
  security:
    enabled:
      false
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE:discovery-service}:8761/eureka/
ribbon:
  http:
    client:
      enabled: true
logging:
  level:
    org.apache.spark: WARN
    org.apache.parquet: WARN
    org.apache.parquet.hadoop: ERROR
    org.hibernate.validator.messageinterpolation: ERROR
    org.apache.hadoop.util.NativeCodeLoader: ERROR
    org.apache.hadoop.conf.Configuration: ERROR
    org.apache.hadoop.mapred: ERROR
    org.springframework.jmx.export.annotation: ERROR
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR
    org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor: ERROR
    org.springframework.context.annotation.ConfigurationClassPostProcessor: ERROR
    org.springframework.boot.web.servlet: ERROR
    com.netflix.config.sources.URLConfigurationSource: ERROR
recommendation:
  dataPath: ${DATA_PATH:/data/spark/data}
  modelPath: ${MODEL_PATH:/data/spark/model}