spring:
  profiles:
    active: development
---
spring:
  profiles: development
  jpa:
    show_sql: false
    # deprecated:
    #database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
server:
  port: 8282
security:
  oauth2:
    resource:
      filter-order: 3
      jwt:
        key-value: aTokenSigningKey
    client:
      client-id: acme
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  http:
    client:
      enabled: true
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://${MYSQL_SERVER:mysql}:3306/dev
    username: root
    password: d4t4b4s3p4s$w0rd!
    initialize: true
    continue-on-error: false
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  port: 8282
security:
  oauth2:
    resource:
      filter-order: 3
      jwt:
        key-value: aTokenSigningKey
    client:
      client-id: acme
management:
  security:
    enabled:
      false
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE:discovery-service}:8761/eureka/
ribbon:
  http:
    client:
      enabled: true
---
spring:
  application:
    name: travel-destination-service
  profiles: test
  jpa:
    show_sql: false
    # deprecated:
    #database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
security:
  oauth2:
    resource:
      filter-order: 3
      jwt:
        key-value: aTokenSigningKey
    client:
      client-id: acme
ribbon:
  http:
    client:
      enabled: true