spring:
  profiles:
    active: development
---
security:
  user:
    password: password
  enable-csrf: false
spring:
  profiles: cloud
---
server:
  port: 8181
security:
  oauth2:
    resource:
      filter-order: 3
  user:
    password: password
  enable-csrf: false
management:
  security:
    enabled:
      false
logging.level.org.springframework.security: DEBUG
spring:
  profiles: development
  jpa:
    show_sql: false
    # deprecated:
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8181
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
server:
  port: 8181
security:
  oauth2:
    resource:
      filter-order: 3
  user:
    password: password
  enable-csrf: false
management:
  security:
    enabled:
      false
logging.level.org.springframework.security: DEBUG
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/dev
    username: root
    password: dbpass
    initialize: true
  jpa:
    hibernate:
      ddl-auto: create-drop
eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8181
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
---
spring:
  profiles: test
  jpa:
    show_sql: false
    # deprecated:
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false
